name: Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 # Updated to v4

      - name: Setup Node
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: 20

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project (Production)
        if: github.ref == 'refs/heads/main'
        run: npm run build -- --mode production

      - name: Build project (Staging)
        if: github.ref == 'refs/heads/staging'
        run: npm run build -- --mode staging

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4 # Updated to v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages (Production)
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Deploy to GitHub Pages (Staging)
        if: github.ref == 'refs/heads/staging'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: staging
